#!/usr/bin/perl

# chilli - ChilliSpot.org. A Wireless LAN Access Point Controller
# Copyright (C) 2003, 2004 Mondru AB.
#
# The contents of this file may be used under the terms of the GNU
# General Public License Version 2, provided that the above copyright
# notice and this permission notice is included in all copies or
# substantial portions of the software.

# Redirects from ChilliSpot daemon:
#
# Redirection when not yet or already authenticated
#   notyet:  ChilliSpot daemon redirects to login page.
#   already: ChilliSpot daemon redirects to success status page.
#
# Response to login:
#   already: Attempt to login when already logged in.
#   failed:  Login failed
#   success: Login succeded
#
# logoff:  Response to a logout


# Shared secret used to encrypt challenge with. Prevents dictionary attacks.
# You should change this to your own shared secret.
#$uamsecret = "ht2eb8ej6s4et3rg1ulp";
$uamsecret = "ht2eb8ej6s4et3rg1ulp";


# Uncomment the following line if you want to use ordinary user-password
# for radius authentication. Must be used together with $uamsecret.
$userpassword=1;

# Our own path
$loginpath = $ENV{'SCRIPT_URL'};
$loginpath = "/cgi-bin/hotspotlogin.cgi";


print STDERR "\n\nhotspotlogin.cgi:::: ENTER :::::\n\n";

print STDERR "loginpath: $loginpath\n";

use Digest::MD5  qw(md5 md5_hex md5_base64);

# Make sure that the form parameters are clean
$OK_CHARS='-a-zA-Z0-9_.@&=%!';
$| = 1;
if ($ENV{'CONTENT_LENGTH'}) {
    read (STDIN, $_, $ENV{'CONTENT_LENGTH'});
}
s/[^$OK_CHARS]/_/go;
$input = $_;


# Make sure that the get query parameters are clean
$OK_CHARS='-a-zA-Z0-9_.@&=%!';
$_ = $query=$ENV{QUERY_STRING};
s/[^$OK_CHARS]/_/go;
$query = $_;


# If she did not use https tell her that it was wrong.
#if (!($ENV{HTTPS} =~ /^on$/)) {
#    print "Content-type: text/html\n\n
#<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">
#<html>
#<head>
#  <title>ChilliSpot Login Failed</title>
#  <meta http-equiv=\"Cache-control\" content=\"no-cache\">
#  <meta http-equiv=\"Pragma\" content=\"no-cache\">
#</head>
#<body bgColor = '#c0d8f4'>
#  <h1 style=\"text-align: center;\">ChilliSpot Login Failed</h1>
#  <center>
#    Login must use encrypted connection.
#  </center>
#</body>
#<!--
#<?xml version=\"1.0\" encoding=\"UTF-8\"?>
#<WISPAccessGatewayParam 
#  xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"
#  xsi:noNamespaceSchemaLocation=\"http://www.acmewisp.com/WISPAccessGatewayParam.xsd\">
#<AuthenticationReply>
#<MessageType>120</MessageType>
#<ResponseCode>102</ResponseCode>
#<ReplyMessage>Login must use encrypted connection</ReplyMessage>
#</AuthenticationReply> 
#</WISPAccessGatewayParam>
#-->
#</html>
#";
#    exit(0);
#}


#Read form parameters which we care about
@array = split('&',$input);
foreach $var ( @array )
{
    @array2 = split('=',$var);
    if ($array2[0] =~ /^UserName$/) { $username = $array2[1]; }
    if ($array2[0] =~ /^Password$/) { $password = $array2[1]; }
    if ($array2[0] =~ /^challenge$/) { $challenge = $array2[1]; }
    if ($array2[0] =~ /^button$/) { $button = $array2[1]; }
    if ($array2[0] =~ /^logout$/) { $logout = $array2[1]; }
    if ($array2[0] =~ /^prelogin$/) { $prelogin = $array2[1]; }
    if ($array2[0] =~ /^res$/) { $res = $array2[1]; }
    if ($array2[0] =~ /^uamip$/) { $uamip = $array2[1]; }
    if ($array2[0] =~ /^uamport$/) { $uamport = $array2[1]; }
    if ($array2[0] =~ /^userurl$/)   { $userurl = $array2[1]; }
    if ($array2[0] =~ /^timeleft$/)  { $timeleft = $array2[1]; }
    if ($array2[0] =~ /^redirurl$/)  { $redirurl = $array2[1]; }
}

#Read query parameters which we care about
@array = split('&',$query);
foreach $var ( @array )
{
    @array2 = split('=',$var);
    if ($array2[0] =~ /^res$/)       { $res = $array2[1]; }
    if ($array2[0] =~ /^challenge$/) { $challenge = $array2[1]; }
    if ($array2[0] =~ /^uamip$/)     { $uamip = $array2[1]; }
    if ($array2[0] =~ /^uamport$/)   { $uamport = $array2[1]; }
    if ($array2[0] =~ /^reply$/)     { $reply = $array2[1]; }
    if ($array2[0] =~ /^userurl$/)   { $userurl = $array2[1]; }
    if ($array2[0] =~ /^timeleft$/)  { $timeleft = $array2[1]; }
    if ($array2[0] =~ /^redirurl$/)  { $redirurl = $array2[1]; }
}

print STDERR "res = |$res|\n";
print STDERR "challenge = |$challenge|\n";
print STDERR "uamip = |$uamip|\n";
print STDERR "uamport = |$uamport|\n";
print STDERR "reply = |$reply|\n";
print STDERR "userurl = |$userurl|\n";
print STDERR "timeleft = |$timeleft|\n";
print STDERR "redirurl = |$redirurl|\n";

$reply =~ s/\+/ /g;
$reply =~s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/seg;

$userurldecode = $userurl;
$userurldecode =~ s/\+/ /g;
$userurldecode =~s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/seg;

$redirurldecode = $redirurl;
$redirurldecode =~ s/\+/ /g;
$redirurldecode =~s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/seg;

$password =~ s/\+/ /g;
$password =~s/%([a-fA-F0-9][a-fA-F0-9])/pack("C", hex($1))/seg;

# If attempt to login
if ($button =~ /^Login$/) {
    $hexchal  = pack "H32", $challenge;
    if (defined $uamsecret) {
	$newchal  = md5($hexchal, $uamsecret);
    }
    else {
	$newchal  = $hexchal;
    }
    $response = md5_hex("\0", $password, $newchal);
    $pappassword = unpack "H32", ($password ^ $newchal);
#sleep 5;
print "Content-type: text/html\n\n";
print "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">
<html>
<head>
  <title>Zoom Internet Login</title>
  <meta http-equiv=\"Cache-control\" content=\"no-cache\">
  <meta http-equiv=\"Pragma\" content=\"no-cache\">";
    if ((defined $uamsecret) && defined($userpassword)) {
	print "  <meta http-equiv=\"refresh\" content=\"0;url=http://$uamip:$uamport/logon?username=$username&password=$pappassword&userurl=$userurl\">";
    } else {
	print "  <meta http-equiv=\"refresh\" content=\"0;url=http://$uamip:$uamport/logon?username=$username&response=$response&userurl=$userurl\">";
    }
print <<END;
  <style type="text/css">
    * { margin: 0; padding: 0; }
    body { margin: 5px; background-color: #edd91d; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; }
    table { empty-cells: show; }
    .switchgroup1 { vertical-align: top; }
    div#tab1, div#tab2 {  overflow: auto; background-color: #ffffff; color: #000000; text-align: left; vertical-align: top; padding: 10px; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; }
    div#tab1 li, div#tab2 li { padding-left: 20px; }
    a:link, a:visited { color: #175BA1; }
    a:hover, a:active { color: #002D5C; }
    .bold {	font-weight: bold; }
    
    div#tab_list { padding: 0; margin: 0; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; text-align: left; vertical-align: bottom; }
    div#tab_list h3 { display: inline; padding: 0px 0px 5px 5px; background: #ffffff url('/tab-topleft.gif') top left no-repeat; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; }
    div#tab_list h3 a { padding: 0px 5px 5px 0; text-decoration: none; background: url('/tab-topright.gif') top right no-repeat;}
    div#tab_list h3 a:link { color: black;}
    div#tab_list h3 a:visited { color: gray;}
    
    .center { text-align: center; }
  </style>
</head>
<body bgColor = '#c0d8f4'>
   <p class="center"><img src="/logo_zoom_hotspot.gif" alt="Armstrong Zoom Internet Hot Spot" /></p>
   <table style="border-collapse: collapse; text-align: center; margin-left: auto; margin-right: auto;">
      <tr>
         <td style="width: 29px; height: 29px;"><img src="/topleft.gif" alt="" /></td>
         <td style="background-image: url('/top.gif'); background-repeat: repeat-x;"></td>
         <td style="width: 29px; height: 29px;"><img src="/topright.gif" alt="" /></td>
      </tr>
      <tr>
         <td style="background-image: url('/left.gif'); background-repeat: repeat-y;"></td>
         <td style="background-color: #014baa; color: #ffffff;">
            <table style="border-collapse: collapse;">
               <tr>
                  <td style="display: table-cell; vertical-align: top;">
                     <table class="login_form">
                       <tr><td></td></tr>
                       <tr>
                         <td align="center" style="padding-top: 10px; color: white; background-color: inherit;">
                          <h1 style="text-align: center;">Logging in to Zoom Internet</h1>
                          <center>
                            Please wait......
                          </center>
                         </td>
                       </tr>
                     </table>
                  </td>
               </tr>
               <tr>
                  <td colspan="2">
                     <p style="padding-top: 15px; background-color: inherit; color: #ffffff; text-align: center; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px;">By proceeding beyond this page you agree to the BCFLS Internet/Wifi Computing Policy and Armstrong Terms &amp; Conditions.</p>
                  </td>
            </table>
         </td>
         <td style="background-image: url('/right.gif'); background-repeat: repeat-y;"></td>
      </tr>
      <tr>
         <td style="width: 29px; height: 30px;"><img src="/bottomleft.gif" alt="" /></td>
         <td style="background-image: url('/bottom.gif'); background-repeat: repeat-x;"></td>
         <td style="width: 29px; height: 30px;"><img src="/bottomright.gif" alt="" /></td>
      </tr>
   </table>

   <p class="center" style="padding-top: 15px;"><img src="/logo_armstrong.gif" alt="Armstrong" /></p>
</body>
<!--
<?xml version="1.0" encoding="UTF-8"?>
<WISPAccessGatewayParam 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="http://www.acmewisp.com/WISPAccessGatewayParam.xsd">
<AuthenticationReply>
<MessageType>120</MessageType>
<ResponseCode>201</ResponseCode>
END
    if ((defined $uamsecret) && defined($userpassword)) {
	print "<LoginResultsURL>http://$uamip:$uamport/logon?username=$username&password=$pappassword</LoginResultsURL>";
    } else {
	print "<LoginResultsURL>http://$uamip:$uamport/logon?username=$username&response=$response&userurl=$userurl</LoginResultsURL>";
    }
print <<END;
</AuthenticationReply> 
</WISPAccessGatewayParam>
-->
</html>
END
    exit(0);
}


# Default: It was not a form request
$result = 0;

# If login successful
if ($res =~ /^success$/) { 
    $result = 1;
}

# If login failed 
if ($res =~ /^failed$/) { 
    $result = 2;
}

# If logout successful
if ($res =~ /^logoff$/) { 
    $result = 3;
}

# If tried to login while already logged in
if ($res =~ /^already$/) { 
    $result = 4;
}

# If not logged in yet
if ($res =~ /^notyet$/) { 
    $result = 5;
}

# If login from smart client
if ($res =~ /^smartclient$/) { 
    $result = 6;
}

# If requested a logging in pop up window
if ($res =~ /^popup1$/) { 
    $result = 11;
}

# If requested a success pop up window
if ($res =~ /^popup2$/) { 
    $result = 12;
}

# If requested a logout pop up window
if ($res =~ /^popup3$/) { 
    $result = 13;
}


# Otherwise it was not a form request
# Send out an error message
if ($result == 0) {
    print "Content-type: text/html\n\n";
    print <<END;
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <title>Zoom Internet Login Failed</title>
  <meta http-equiv="Cache-control" content="no-cache">
  <meta http-equiv="Pragma" content="no-cache">
  <style type="text/css">
    * { margin: 0; padding: 0; }
    body { margin: 5px; background-color: #edd91d; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; }
    table { empty-cells: show; }
    .switchgroup1 { vertical-align: top; }
    div#tab1, div#tab2 {  overflow: auto; background-color: #ffffff; color: #000000; text-align: left; vertical-align: top; padding: 10px; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; }
    div#tab1 li, div#tab2 li { padding-left: 20px; }
    a:link, a:visited { color: #175BA1; }
    a:hover, a:active { color: #002D5C; }
    .bold {	font-weight: bold; }
    
    div#tab_list { padding: 0; margin: 0; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; text-align: left; vertical-align: bottom; }
    div#tab_list h3 { display: inline; padding: 0px 0px 5px 5px; background: #ffffff url('/tab-topleft.gif') top left no-repeat; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; }
    div#tab_list h3 a { padding: 0px 5px 5px 0; text-decoration: none; background: url('/tab-topright.gif') top right no-repeat;}
    div#tab_list h3 a:link { color: black;}
    div#tab_list h3 a:visited { color: gray;}
    
    .center { text-align: center; }
  </style>
</head>
<body bgColor = '#c0d8f4'>
   <p class="center"><img src="/logo_zoom_hotspot.gif" alt="Armstrong Zoom Internet Hot Spot" /></p>
   <table style="border-collapse: collapse; text-align: center; margin-left: auto; margin-right: auto;">
      <tr>
         <td style="width: 29px; height: 29px;"><img src="/topleft.gif" alt="" /></td>
         <td style="background-image: url('/top.gif'); background-repeat: repeat-x;"></td>
         <td style="width: 29px; height: 29px;"><img src="/topright.gif" alt="" /></td>
      </tr>
      <tr>
         <td style="background-image: url('/left.gif'); background-repeat: repeat-y;"></td>
         <td style="background-color: #014baa; color: #ffffff;">
            <table style="border-collapse: collapse;">
               <tr>
                  <td style="display: table-cell; vertical-align: top;">
                     <table class="login_form">
                       <tr><td></td></tr>
                       <tr>
                         <td align="center" style="padding-top: 10px; color: white; background-color: inherit;">
                          <h1 style="text-align: center;">Zoom Internet Login Failed</h1>
                          <center>
                            Login must be performed through the Zoom Internet Portal.
                          </center>
                         </td>
                       </tr>
                     </table>
                  </td>
               </tr>
               <tr>
                  <td colspan="2">
                     <p style="padding-top: 15px; background-color: inherit; color: #ffffff; text-align: center; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px;">By proceeding beyond this page you agree to the BCFLS Internet/Wifi Computing Policy and Armstrong Terms &amp; Conditions.</p>
                  </td>
            </table>
         </td>
         <td style="background-image: url('/right.gif'); background-repeat: repeat-y;"></td>
      </tr>
      <tr>
         <td style="width: 29px; height: 30px;"><img src="/bottomleft.gif" alt="" /></td>
         <td style="background-image: url('/bottom.gif'); background-repeat: repeat-x;"></td>
         <td style="width: 29px; height: 30px;"><img src="/bottomright.gif" alt="" /></td>
      </tr>
   </table>

   <p class="center" style="padding-top: 15px;"><img src="/logo_armstrong.gif" alt="Armstrong" /></p>
</body>
</html>
END

    exit(0);
}

#Generate the output
print "Content-type: text/html\n\n";
print <<END;
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
<head>
  <title>Zoom Internet Login</title>
  <meta http-equiv="Cache-control" content="no-cache">
  <meta http-equiv="Pragma" content="no-cache">
  <SCRIPT LANGUAGE="JavaScript">
    var blur = 0;
    var starttime = new Date();
    var startclock = starttime.getTime();
    var mytimeleft = 0;

    function doTime() {
      window.setTimeout( "doTime()", 1000 );
      t = new Date();
      time = Math.round((t.getTime() - starttime.getTime())/1000);
      if (mytimeleft) {
        time = mytimeleft - time;
        if (time <= 0) {
          window.location = "$loginpath?res=popup3&uamip=$uamip&uamport=$uamport";
        }
      }
      if (time < 0) time = 0;
      hours = (time - (time % 3600)) / 3600;
      time = time - (hours * 3600);
      mins = (time - (time % 60)) / 60;
      secs = time - (mins * 60);
      if (hours < 10) hours = "0" + hours;
      if (mins < 10) mins = "0" + mins;
      if (secs < 10) secs = "0" + secs;
      title = "Online time: " + hours + ":" + mins + ":" + secs;
      if (mytimeleft) {
        title = "Remaining time: " + hours + ":" + mins + ":" + secs;
      }
      if(document.all || document.getElementById){
         document.title = title;
      }
      else {   
        self.status = title;
      }
    }

    function popUp(URL) {
      if (self.name != "chillispot_popup") {
        chillispot_popup = window.open(URL, 'chillispot_popup', 'toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=500,height=375');
      }
    }

    function doOnLoad(result, URL, userurl, redirurl, timeleft) {
      if (timeleft) {
        mytimeleft = timeleft;
      }
      if ((result == 1) && (self.name == "chillispot_popup")) {
        doTime();
      }
      if ((result == 1) && (self.name != "chillispot_popup")) {
        chillispot_popup = window.open(URL, 'chillispot_popup', 'toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=500,height=375');
      }
      if ((result == 2) || result == 5) {
        document.form1.UserName.focus()
      }
      if ((result == 2) && (self.name != "chillispot_popup")) {
        chillispot_popup = window.open('', 'chillispot_popup', 'toolbar=0,scrollbars=0,location=0,statusbar=0,menubar=0,resizable=0,width=400,height=200');
        chillispot_popup.close();
      }
      if ((result == 12) && (self.name == "chillispot_popup")) {
        doTime();
        if (redirurl) {
          opener.location = redirurl;
        }
        else if (userurl) {
          opener.location = userurl;
        }
        else if (opener.home) {
          opener.home();
        }
        else {
          opener.location = "about:home";
        }
        self.focus();
        blur = 0;
      }
      if ((result == 13) && (self.name == "chillispot_popup")) {
        self.focus();
        blur = 1;
      }
    }

    function doOnBlur(result) {
      if ((result == 12) && (self.name == "chillispot_popup")) {
        if (blur == 0) {
          blur = 1;
          self.focus();
        }
      }
    }
  </script>
  <meta http-equiv="Cache-control" content="no-cache">
  <meta http-equiv="Pragma" content="no-cache">
  <style type="text/css">
    * { margin: 0; padding: 0; }
    body { margin: 5px; background-color: #edd91d; color: #000000; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; }
    table { empty-cells: show; }
    .switchgroup1 { vertical-align: top; }
    div#tab1, div#tab2 {  overflow: auto; background-color: #ffffff; color: #000000; text-align: left; vertical-align: top; padding: 10px; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; }
    div#tab1 li, div#tab2 li { padding-left: 20px; }
    a:link, a:visited { color: #175BA1; }
    a:hover, a:active { color: #002D5C; }
    .bold {	font-weight: bold; }
    
    div#tab_list { padding: 0; margin: 0; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; text-align: left; vertical-align: bottom; }
    div#tab_list h3 { display: inline; padding: 0px 0px 5px 5px; background: #ffffff url('/tab-topleft.gif') top left no-repeat; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px; }
    div#tab_list h3 a { padding: 0px 5px 5px 0; text-decoration: none; background: url('/tab-topright.gif') top right no-repeat;}
    div#tab_list h3 a:link { color: black;}
    div#tab_list h3 a:visited { color: gray;}
    
    .center { text-align: center; }
  </style>
</head>
<body onLoad="javascript:doOnLoad($result, '$loginpath?res=popup2&uamip=$uamip&uamport=$uamport&userurl=$userurl&redirurl=$redirurl&timeleft=$timeleft','$userurldecode', '$redirurldecode', '$timeleft')" onBlur = "javascript:doOnBlur($result)" bgColor = '#c0d8f4'>
	<p class="center"><img src="/logo_zoom_hotspot.gif" alt="Armstrong Zoom Internet Hot Spot" /></p>
	<table style="border-collapse: collapse; text-align: center; margin-left: auto; margin-right: auto;">
		<tr>
			<td style="width: 29px; height: 29px;"><img src="/topleft.gif" alt="" /></td>
			<td style="background-image: url('/top.gif'); background-repeat: repeat-x;"></td>
			<td style="width: 29px; height: 29px;"><img src="/topright.gif" alt="" /></td>
		</tr>
		<tr>
			<td style="background-image: url('/left.gif'); background-repeat: repeat-y;"></td>
			<td style="background-color: #014baa; color: #ffffff;">
END


#      if (!window.opener) {
#        document.bgColor = '#c0d8f4';
#      }

#print "THE INPUT: $input";
#foreach $key (sort (keys %ENV)) {
#   print $key, ' = ', $ENV{$key}, "<br>\n";
#}

if ($result == 2) {
    print <<END;
  <h1 style="text-align: center;">Zoom Internet Login Failed</h1>
END
    if ($reply) {
   print "<center> $reply </BR></BR></center>";
    }
}

if ($result == 2 || $result == 5) {
  print STDERR "result: $result, loginpath: $loginpath\n";

  print <<END;
				<table style="border-collapse: collapse;">
					<tr>
						<td>
							<div id="tab_list">
								<h3 style="color: #000000; background-color: #ffffff;"><a>Armstrong Terms &amp; Conditions</a></h3>
							</div> <!-- end div tab_list-->
						</td>
					</tr>
					<tr>
						<td style="display: table-cell; vertical-align: top;">
							<div id="tab2" class="switchgroup1">
								<p>This Web site is an online information and communication service provided by Armstrong and its affiliated companies. Please read these terms of use carefully before using this site. By using this site, you signify your agreement with these Terms of Use. If you do not agree with any of the below Terms of Use, do not use this site. Armstrong reserves the right, in its sole discretion, to modify, alter or otherwise update these Terms of Use at any time. Such modifications shall be effective immediately upon the posting of the modified Terms of Use. By using this service after we have posted notice of such modifications, alterations or updates, you agree to be bound by the revised terms.<br /><br /></p>
								<p>Armstrong retains the right to deny access to anyone at its complete discretion for any reason including for violations of these Terms of Use. This Web site provides links to many other Web sites not affiliated with Armstrong that may have a Terms of Use Policy different from, or in addition to, the Terms of Use specified herein, particularly in the case of Web sites hosting third party content or that allow posting by third parties. By accessing such Web sites through links provided on this Web site, you agree to abide by each applicable Terms of Use Policy as therein specified.</p>	
							</div> <!-- end div tab2 -->
						</td>
						<td style="display: table-cell; text-align: center; color: white; background-color: inherit; padding: 10px;">
							<div id="div_asid_5" style="display: inline;">
                     <form name="form1" method="post" action="$loginpath">
                     <INPUT TYPE="hidden" NAME="challenge" VALUE="$challenge">
                     <INPUT TYPE="hidden" NAME="uamip" VALUE="$uamip">
                     <INPUT TYPE="hidden" NAME="uamport" VALUE="$uamport">
                     <INPUT TYPE="hidden" NAME="userurl" VALUE="$userurldecode">
		     <INPUT TYPE="hidden" name="UserName" VALUE="foo1">
 		     <INPUT TYPE="hidden" name="Password" VALUE="bar1">
							<table class="login_form">
							  <tr><td></td></tr>
							  <tr>
							    <td align="center" style="padding-top: 10px; color: white; background-color: inherit;">
							      By clicking this button and logging into the Zoom Internet Service, I agree to the terms and conditions stated above. <br><br>		
                              <input type="submit" name="button" value="Login" onClick="javascript:popUp('$loginpath?res=popup1&uamip=$uamip&uamport=$uamport')">
							    </td>
							  </tr>
							</table>
							</%method>
							</form></div>
						</td>
					</tr>
					<tr>
						<td colspan="2">
							<p style="padding-top: 15px; background-color: inherit; color: #ffffff; text-align: center; font-family: Verdana, Arial, Helvetica, sans-serif; font-size: 12px;">By proceeding beyond this page you agree to the BCFLS Internet/Wifi Computing Policy and Armstrong Terms &amp; Conditions.</p>
						</td>
				</table>
			</td>
			<td style="background-image: url('/right.gif'); background-repeat: repeat-y;"></td>
		</tr>
		<tr>
			<td style="width: 29px; height: 30px;"><img src="/bottomleft.gif" alt="" /></td>
			<td style="background-image: url('/bottom.gif'); background-repeat: repeat-x;"></td>
			<td style="width: 29px; height: 30px;"><img src="/bottomright.gif" alt="" /></td>
		</tr>
	</table>

	<p class="center" style="padding-top: 15px;"><img src="/logo_armstrong.gif" alt="Armstrong" /></p>
	
</body>
</html>
END
}

if ($result == 1) {
  print <<END;
           <h1 style="text-align: center;">Logged in</h1>
END
  if ($reply) { 
      print "<center> $reply </BR></BR></center>";
  }

  print <<END;
  <center>
    <a href="https://$uamip:$uamport/logoff">Logout</a>
  </center>
			</td>
			<td style="background-image: url('/right.gif'); background-repeat: repeat-y;"></td>
		</tr>
		<tr>
			<td style="width: 29px; height: 30px;"><img src="/bottomleft.gif" alt="" /></td>
			<td style="background-image: url('/bottom.gif'); background-repeat: repeat-x;"></td>
			<td style="width: 29px; height: 30px;"><img src="/bottomright.gif" alt="" /></td>
		</tr>
	</table>

	<p class="center" style="padding-top: 15px;"><img src="/logo_armstrong.gif" alt="Armstrong" /></p>
	
</body>
</html>
END
}

if (($result == 4) || ($result == 12)) {
  print <<END;
            <h1 style="text-align: center;">Logged in</h1>
            <center>
               <a href="https://$uamip:$uamport/logoff">Logout</a>
            </center>
			</td>
			<td style="background-image: url('/right.gif'); background-repeat: repeat-y;"></td>
		</tr>
		<tr>
			<td style="width: 29px; height: 30px;"><img src="/bottomleft.gif" alt="" /></td>
			<td style="background-image: url('/bottom.gif'); background-repeat: repeat-x;"></td>
			<td style="width: 29px; height: 30px;"><img src="/bottomright.gif" alt="" /></td>
		</tr>
	</table>

	<p class="center" style="padding-top: 15px;"><img src="/logo_armstrong.gif" alt="Armstrong" /></p>
	
</body>
</html>
END
}


if ($result == 11) {
   print <<END;
           <h1 style="text-align: center;">Logging in to Zoom Internet</h1>
           <center>
             Here! Please wait......
           </center>
			</td>
			<td style="background-image: url('/right.gif'); background-repeat: repeat-y;"></td>
		</tr>
		<tr>
			<td style="width: 29px; height: 30px;"><img src="/bottomleft.gif" alt="" /></td>
			<td style="background-image: url('/bottom.gif'); background-repeat: repeat-x;"></td>
			<td style="width: 29px; height: 30px;"><img src="/bottomright.gif" alt="" /></td>
		</tr>
	</table>

	<p class="center" style="padding-top: 15px;"><img src="/logo_armstrong.gif" alt="Armstrong" /></p>
	
</body>
</html>
END
}


if (($result == 3) || ($result == 13)) {
   print <<END;
           <h1 style="text-align: center;">Logged out from Zoom Internet</h1>
           <center>
             <a href="https://$uamip:$uamport/prelogin">Login</a>
           </center>
			</td>
			<td style="background-image: url('/right.gif'); background-repeat: repeat-y;"></td>
		</tr>
		<tr>
			<td style="width: 29px; height: 30px;"><img src="/bottomleft.gif" alt="" /></td>
			<td style="background-image: url('/bottom.gif'); background-repeat: repeat-x;"></td>
			<td style="width: 29px; height: 30px;"><img src="/bottomright.gif" alt="" /></td>
		</tr>
	</table>

	<p class="center" style="padding-top: 15px;"><img src="/logo_armstrong.gif" alt="Armstrong" /></p>
	
</body>
</html>
END
}


exit(0);

